version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  db_migrator:
    image: migrate/migrate
    volumes:
      - ./service/database/migrations:/migrations
    entrypoint: ["migrate", "-path", "/migrations/", "-database", "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE}", "up"]
    links:
      - db
    depends_on:
      - "db"

  service:
    image: url_shortener
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    links:
      - db
    depends_on:
      - "db"
      - "db_migrator"